package ca.weblite.swete;


import ca.weblite.swete.forms.SiteForm;
import ca.weblite.swete.forms.WelcomeForm;
import ca.weblite.swete.models.Settings;
import ca.weblite.swete.models.WebSite;
import ca.weblite.swete.services.JobQueue;
import static com.codename1.ui.CN.*;
import com.codename1.ui.Display;
import com.codename1.ui.Form;
import com.codename1.ui.Dialog;
import com.codename1.ui.Label;
import com.codename1.ui.plaf.UIManager;
import com.codename1.ui.util.Resources;
import com.codename1.io.Log;
import com.codename1.ui.Toolbar;
import java.io.IOException;
import com.codename1.ui.layouts.BoxLayout;
import com.codename1.io.NetworkEvent;
import com.codename1.io.Util;


/**
 * This file was generated by <a href="https://www.codenameone.com/">Codename One</a> for the purpose 
 * of building native mobile applications using Java.
 */
public class SweteApp {

    private JobQueue jobQueue;
    private static SweteApp instance;
    
    private Form current;
    private Resources theme;

    public void init(Object context) {
        instance = this;
        // use two network threads instead of one
        updateNetworkThreadCount(2);

        theme = UIManager.initFirstTheme("/theme");

        // Enable Toolbar on all Forms by default
        Toolbar.setGlobalToolbar(true);

        // Pro only feature
        Log.bindCrashProtection(true);

        addNetworkErrorListener(err -> {
            // prevent the event from propagating
            err.consume();
            if(err.getError() != null) {
                Log.e(err.getError());
            }
            Log.sendLogAsync();
            Dialog.show("Connection Error", "There was a networking error in the connection to " + err.getConnectionRequest().getUrl(), "OK", null);
        });  
        
        Util.register(new WebSite());
        Util.register(new Settings());
        jobQueue = new JobQueue();
        
    }
    
    public void start() {
        if(current != null){
            current.show();
            return;
        }
        /*
        WebSite site = new WebSite();
        site.setName("A2 Hosting");
        site.setSrcUrl("https://mx.www.a2hosting.com/");
        site.setProxyUrl("https://www.a2hosting.com.mx/");
        site.setSiteId("428");
        Form hi = new SiteForm(site);
        
        hi.show();
        */
        try {
            WelcomeForm form = new WelcomeForm(Settings.getInstance());
            form.show();
        } catch (IOException ex) {
            Log.e(ex);
        }
    }

    public void stop() {
        current = getCurrentForm();
        if(current instanceof Dialog) {
            ((Dialog)current).dispose();
            current = getCurrentForm();
        }
    }
    
    public void destroy() {
    }
    
    public static SweteApp getInstance() {
        return instance;
    }
    
    public JobQueue getJobQueue() {
        return jobQueue;
    }

}
